<?php

namespace Terah\Saasu\Values;


/**
 * Class TaxCodeDetail
 *
 * @package Terah\Saasu\Values
 */
class TaxCodeDetail extends RestableValue
{
    /**
     * Custom notes associated with this tax code (if any).
     * @var string
     */
    public $Notes                   = '';

    /**
     * The Id/key of this resource.
     * @var int
     */
    public $Id                      = null;

    /**
     * The actual tax code.
     * @var string
     */
    public $Code                    = '';

    /**
     * The name of this tax code.
     * @var string
     */
    public $Name                    = '';

    /**
     * The rate associated with this tax code.
     * @var int
     */
    public $Rate                    = null;

    /**
     * The account tax amounts are posted to when used in transactions.
     * @var int
     */
    public $PostingAccountId        = null;

    /**
     * Tax code could be used in Sale transactions.
     * @var bool
     */
    public $IsSale                  = true;

    /**
     * Tax code could be used in Purchase transactions.
     * @var bool
     */
    public $IsPurchase              = false;

    /**
     * Tax code could be used in Payroll transactions. NOTE: This only applies to inbuilt tax codes.
     * @var bool
     */
    public $IsPayroll               = true;

    /**
     * Indicates if the Tax code was generated by the system.
     * @var bool
     */
    public $IsInbuilt               = false;

    /**
     * Indicates if the tax code is shared.
     * @var bool
     */
    public $IsShared                = true;

    /**
     * Indicates if the tax code is currently set to active.
     * @var bool
     */
    public $IsActive                = true;

    /**
     * The date and time that this resource was created in UTC.
     * @var DateTime
     */
    public $CreatedDateUtc          = '';

    /**
     * The date and time that this resource was last modified in UTC.
     * @var DateTime
     */
    public $LastModifiedDateUtc     = '';

    /**
     * The user id that last modified this resource
     * @var int
     */
    public $LastModifiedByUserId    = null;

    /**
     * The unique Id for this version of the record which is required to be passed in when next updating this resource.
     * @var string
     */
    public $LastUpdatedId           = '';

    /**
     * Hypermedia links.
     * Contains contextual links to possible next actions related to this resource.
     * Only present in responses.
     * This data is not to be sent to the server.
     * Collection ofLink
     * @var array
     */
    public $_links                  = [];
}
